### ISSUE TITLE
Question on file revisions

### ISSUE THREAD

**Issue by sethhillbrand** [KiCad/kicad-packages3D-source#87]
Hi All-

I'd like to submit some revised files for the Pin Headers and Pin Connectors.  Right now, for example, the PinHeader_2x40_P1.00mm_Horizontal.step takes 2.9MB.  When I generate an equivalent model in SolidWorks, export to STEP and post-process, it is 91k.

I'd like to generate models for the full Connector set using the same toolpath but it does take a fair bit of work, so I'd like to check in with the maintainers on whether this would be worth doing or whether keeping the models in FreeCAD is worth the extra space.  For reference, the 1.0mm PinHeader directory looks to be about 25MB when generated this way instead of the 346MB.

I'm attaching the 2x40 P1.0mm Horizontal STEP file below.  I'd love any comments on things that need to be changed before this type of PR would be accepted.

[PinHeader_2x40_P1.00mm_Horizontal.step.zip](https://github.com/KiCad/kicad-packages3D-source/files/1650097/PinHeader_2x40_P1.00mm_Horizontal.step.zip)

**Comment by easyw** [comment]
The attached step file is not unioned in to a single object, but an assembly of many objects...
![pin-header](https://user-images.githubusercontent.com/3032347/35199561-0daa9d62-ff00-11e7-8991-1d5819d36d46.PNG)

About the sw used to create the library, FreeCAD is an open source sw, as well as KiCad. For that reason I would stay on a library of models made by a sw that can be accessed by everyone, instead of a commercial sw. Then the library can be modified by every one that will like to contribute.

**Comment by sethhillbrand** [comment]
Just so that I understand (sorry if this is just repeating but I would like to understand):
- Models from Solidworks are not acceptable
- Assemblies are not acceptable.

**Comment by easyw** [comment]
this is only my opinion:

- a library of an open source sw (KiCad) should be a library in which every one could contribute and update the models... then only an open source CAD modeler can be the right choice
- assemblies instead of single part are not suggested for the library

I'm not a developer nor a librarian ... but I started the KiCad MCAD libraries with these assumptions...
@Shackmeister I leave the decision up to you and the others librarians.

**Comment by poeschlr** [comment]
The pin header models are script generated. This is much more easily maintained then any other option.

I don't see a reason why these should be replaced.

**Comment by sethhillbrand** [comment]
I agree, script-generated makes sense.  I wouldn't suggest generating the hundreds of models by hand.  The script I've been working on is SW-specific however, so if commercial software is off-limits, I'll avoid it and spend some time learning FreeCAD.

As to why I wanted to update this:  I was hoping to create a number of manufacturer-specific pin headers and sockets.  The difference of 3-4 mm in pin length and socket base makes a difference for some of the tight clearances I work with.  Unfortunately, at their current size, this would be problematic.  But at a factor of 10 smaller, it becomes realistic.

So I suppose this is two questions:
- Are pull requests generated from SolidWorks models/scripts off-limits?
- Would it be preferable to make the PR for a set of new mfg-specific models rather than updating the generic ones?

**Comment by easyw** [comment]
The issue with a proprietary sw is: who will maintain the library if the committer just left the repo? Only through a free sw every user could help in update the work.
We had already few changes in the library structure that reflected in a massive 3d library changes. Having models made in a proprietary sw would restric the chance to keep the library up to date.

**Comment by antoniovazquezblanco** [comment]
@sethhillbrand what is the status on this issue?

As stated in other comments, it seems that maintainability is the priority so it seems that librarians will not be willing to switch the current scripts that can be executed by anyone for a set of scripts that depend on licensed software.

If the issue is the size of the library maybe there is a way to improve the current scripts or even FreeCAD so that the situation improves.

Were your questions answered or should we keep the issue open?

Thank you

**Comment by sethhillbrand** [comment]
I'd suggest leaving this open until there's a clear guideline for how model source files must be generated.  Currently the documentation (https://github.com/KiCad/kicad-packages3d) says free software is preferred but proprietary is allowed.  The feedback in this thread indicates that is not the case unless I'm misreading the comments.

**Comment by antoniovazquezblanco** [comment]
Could you librarians have a vote on wether proprietary software generated 3D models are allowed and reflect the decision here?

(I would suggest you react with a 👍 emoji to this coment for a "yes, allowed" and a 👎 emoji for a "no, not allowed" if there is no other voting mechanism)

**Comment by poeschlr** [comment]
I would allow them but we will still prefer models by freecad. (I do not like forcing users to use one particular tool over another)

However the final export should be made in freecad using stepup. Meaning the contributor would first export a step from their prefered tool, import that step into freecad. Properly align the footprint and 3d model using stepup. Export a new step/wrl pair using stepup.

**Comment by Shackmeister** [comment]
Exactly what René says.

**Comment by sethhillbrand** [comment]
Yes

**Comment by antoniovazquezblanco** [comment]
Thank you
